name: ci
run-name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TAG: 0.0.${{ github.run_number }}
      FORCE_COLOR: 1
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: setup-qemu
        uses: docker/setup-qemu-action@v3
      - name: login-to-ghcr
        run: echo "Faking it to avoid you having to create a secret with Registry authentication"
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: vfarcic
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      - id: install-devbox
        uses: jetify-com/devbox-install-action@v0.12.0
      - id: run-unit-tests
        run: devbox run -- ./dot.nu run unit_tests
      - name: build-image
        run: echo "Faking it to avoid you having to create a secret with Registry authentication"
      #   run: devbox run -- ./dot.nu build image $TAG
      #   env:
      #     REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - name: update-manifests
        run: echo "Faking it to avoid you having to create secrets with Cosign and Registry authentication"
      #   run: devbox run -- ./dot.nu update manifests $TAG
      #   env:
      #     COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      #     COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      #     REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      - id: delete-neon-branch
        uses: neondatabase/delete-branch-action@v3
        continue-on-error: true
        with:
          project_id: super-darkness-76149530
          branch: silly-demo/${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - id: create-neon-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: super-darkness-76149530
          database: dot_neon
          parent: main
          branch_name: silly-demo/${{ github.event.number }}
          username: dot_owner
          api_key: ${{ secrets.NEON_API_KEY }}
      - id: deploy-app
        run: devbox run -- ./dot.nu deploy app ${{ steps.create-neon-branch.outputs.db_url }}
      - id: run-integration-tests
        run: devbox run -- ./dot.nu run integration_tests ${{ steps.create-neon-branch.outputs.db_url }}
      - name: commit-changes
        run: echo "Faking it since we faked previous tasks that modified files"
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Release ${{ env.TAG }} [skip ci]"
      - name: push-changes
        run: echo "Faking it since we faked previous tasks that modified files"
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
