name: ci
run-name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: All
        run: |
          ls -la
