name: ci
run-name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: neondatabase/delete-branch-action@v3
        id: delete-branch
        continue-on-error: true
        with:
          project_id: super-darkness-76149530
          branch: silly-demo/${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - uses: neondatabase/create-branch-action@v5
        id: create-branch
        with:
          project_id: super-darkness-76149530
          database: dot
          parent: main
          branch_name: silly-demo/${{ github.event.number }}
          username: dot_owner
          api_key: ${{ secrets.NEON_API_KEY }}
      - name: branch-info
        run: |
          echo db_url: ${{ steps.create-branch.outputs.db_url }}
          echo host: ${{ steps.create-branch.outputs.host }}
          echo branch_id: ${{ steps.create-branch.outputs.branch_id }}
